Botnet rebase
sigvartmh/fw-nrfconnect-nrf-1 pull request #29
Opened 2020-08-25 08:31 UTC by sigvartmh

Lets go haaaam

2020-08-25 08:39 UTC, sigvartmh commented on samples/nrf5340/netboot/src/main.c
> +			return;
Missing goto. Should we use `while` + `break` instead?

2020-08-25 08:41 UTC, sigvartmh commented on samples/nrf5340/netboot/src/main.c
> +
maybe add early return?

2020-08-25 10:09 UTC, hakonfam requested changes

2020-08-25 10:09 UTC, hakonfam commented on cmake/mcuboot.cmake
> +    # The bootloader on the network core is enabled. The validation of this
Is it? IT is the inclusion of mcuboot on the app core than implies that the net core bootloader is included. Fix this.

2020-08-25 10:09 UTC, hakonfam commented on cmake/mcuboot.cmake
> +    # need a target for creating the signed binary of the network core
We don't need a target, we need to create the update.

2020-08-25 10:09 UTC, hakonfam commented on cmake/mcuboot.cmake
> +    include(${CMAKE_BINARY_DIR}/hci_rpmsg/shared_vars.cmake)
Add a comment on why this is needed

2020-08-25 10:09 UTC, hakonfam commented on cmake/mcuboot.cmake
> +    # TODO replace with proper domain once PR is in
https://github.com/nrfconnect/sdk-nrf/pull/2527

2020-08-25 10:09 UTC, hakonfam commented on cmake/partition_manager.cmake
> +  # The partition manager script ensures that the 'app' hex always exists.
Remove this comment, it gives no info

2020-08-25 10:09 UTC, hakonfam commented on cmake/partition_manager.cmake
> +      # TODO don't check BOARD, don'c check for BT_RPMSG. Do something smarter, look at domains?
https://github.com/nrfconnect/sdk-nrf/pull/2527

Also, this is no longer a BOARD check, but SoC, which is OK

2020-08-25 10:09 UTC, hakonfam commented on include/dfu/pcd.h
> +/** Magic value written to indicate that a something failed. */
```suggestion
/** Magic value written to indicate that something failed. */
```

2020-08-25 10:09 UTC, hakonfam commented on include/dfu/pcd.h
> +} __attribute__ ((aligned(4)));
Is this how alignment is done elsewhere in NCS?

2020-08-25 10:09 UTC, hakonfam commented on include/dfu/pcd.h
> +#define PCD_CMD_ADDRESS (APP_CORE_SRAM_BASE_ADDRESS + APP_CORE_SRAM_SIZE \
Add some comments here, why does this need to be at this address? What is it used for?

2020-08-25 10:09 UTC, hakonfam commented on include/dfu/pcd.h
> +#if !defined(CONFIG_NRF_SPU_RAM_REGION_SIZE) //&& defined nrf53?
When is this the case?

spm.c use 

```
/* SPU RAM regions */
#define RAM_SECURE_ATTRIBUTION_REGION_SIZE CONFIG_NRF_SPU_RAM_REGION_SIZE
#define NUM_RAM_SECURE_ATTRIBUTION_REGIONS (TOTAL_RAM_SIZE \
				/ RAM_SECURE_ATTRIBUTION_REGION_SIZE)
```

2020-08-25 10:09 UTC, hakonfam commented on include/dfu/pcd.h
> +struct pcd_cmd {
Could we move this inside the  C file, and only have an empty struct definition here? To protect the members, and then update the signature of the `pcd_transfer` method to instead take src, len and offset as arguments.

2020-08-25 10:09 UTC, hakonfam commented on samples/bluetooth/peripheral_uart/prj.conf
> +CONFIG_BOOTLOADER_MCUBOOT=y
```suggestion
```

2020-08-25 10:09 UTC, hakonfam commented on samples/nrf5340/netboot/README.rst
> +This bootloader sample implements an immutable first stage bootloader that has the capability to download update the application firmware on the network core of the nRF5340 SoC.
```suggestion
This bootloader sample implements an immutable first stage bootloader that has the capability to update the application firmware on the network core of the nRF5340 SoC.
```

2020-08-25 10:09 UTC, hakonfam commented on samples/nrf5340/netboot/README.rst
> +#. Lock the flash of the application.
```suggestion
#. Lock the flash of the application partition.
```

2020-08-25 10:09 UTC, hakonfam commented on subsys/pcd/src/pcd.c
> +	return 0;
This should be outside this function

2020-08-25 10:29 UTC, hakonfam commented on include/dfu/pcd.h
> +#define APP_CORE_SRAM_BASE_ADDRESS 0x20000000
DT?

2020-08-26 11:12 UTC, sigvartmh commented on subsys/pcd/src/pcd.c
> +	return 0;
Fixed.

2020-08-27 08:22 UTC, closed without merging